#!/usr/bin/env python3
"""Build the Leantime fa-IR overlay INI from translations/fa-IR.json.

Usage:
  python scripts/build_overlay.py [--out custom/Language/fa-IR.ini]

Reads the canonical translation source (translations/fa-IR.json) and emits the
INI overlay that Leantime loads after the shipped app/Language/fa-IR.ini
(see app/Core/Language.php readIni, CUSTOM_LANG_FOLDER).

The output is upgrade-safe: it never touches vendor files, so a Leantime image
update can be re-paired by re-running this script and redeploying.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "translations" / "fa-IR.json"
VERSION_FILE = ROOT / "translations" / "VERSION"
DEFAULT_OUT = ROOT / "custom" / "Language" / "fa-IR.ini"

PERSIAN_RE = re.compile(r"[؀-ۿ]")


def read_version() -> str:
    if VERSION_FILE.exists():
        return VERSION_FILE.read_text(encoding="utf-8").strip()
    return "unknown"


def validate(trans: dict) -> list[str]:
    problems = []
    for key, entry in trans.items():
        if not isinstance(entry, dict):
            problems.append(f"{key}: not an object")
            continue
        fa = entry.get("fa", "")
        if entry.get("tech") or entry.get("literal"):
            continue
        if not fa:
            problems.append(f"{key}: empty fa value")
        elif not PERSIAN_RE.search(fa):
            problems.append(f"{key}: fa value has no Persian letters: {fa[:60]}")
    return problems


def build(trans: dict) -> str:
    lines = [
        "; Leantime Persian (fa-IR) overlay - 123Service / PPSJ",
        "; Upgrade-safe: loaded AFTER app/Language/fa-IR.ini",
        "; (see app/Core/Language.php readIni, CUSTOM_LANG_FOLDER).",
        "; Source of truth: translations/fa-IR.json - do NOT edit this file,",
        "; edit the JSON and run scripts/build_overlay.py instead.",
        f"; Overlay version: {read_version()}",
        "",
    ]
    for key, entry in trans.items():
        value = str(entry.get("fa", "")).replace('"', "'")
        lines.append(f'{key}="{value}"')
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    ap.add_argument("--check-only", action="store_true")
    args = ap.parse_args()

    if not SOURCE.exists():
        print(f"ERROR: missing {SOURCE}", flush=True)
        return 1

    trans = json.loads(SOURCE.read_text(encoding="utf-8"))
    print(f"loaded {len(trans)} keys from {SOURCE.name}")

    problems = validate(trans)
    if problems:
        print(f"\nVALIDATION FAILED: {len(problems)} problem(s)")
        for p in problems[:30]:
            print("  -", p)
        return 2
    print("validation OK: every non-technical key has a Persian value")

    if args.check_only:
        return 0

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    payload = build(trans)
    out.write_text(payload, encoding="utf-8", newline="\n")
    print(f"\nwrote {out}  ({out.stat().st_size} bytes, {len(trans)} keys)")
    print(f"overlay version: {read_version()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
